WorkManagement/WorkManagement.MVCUI/Controllers/WorkerGalleryManagerController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WorkManagement.Core.Contracts;
using WorkManagement.Core.Models;
using WorkManagement.Core.ViewModels;

namespace WorkManagement.MVCUI.Controllers
{
    public class WorkerGalleryManagerController : Controller
    {
        IRepository<WorkerGallery> _workerGalleryRepository;
        IRepository<Worker> _workerRepository;
      
        public WorkerGalleryManagerController(IRepository<WorkerGallery> workerImageGalleryRepository, IRepository<Worker> workerRepository)
        {
            _workerGalleryRepository = workerImageGalleryRepository;
            _workerRepository = workerRepository;
          
        }
        public ActionResult Index()
        {
            List<WorkerGallery> listOfGallery = _workerGalleryRepository.Collection().ToList();

            return View(listOfGallery);
        }
       
        public ActionResult Create()
        {
            WorkerGalleryViewModel viewModel = new WorkerGalleryViewModel()
            {
                WorkerGallery = new WorkerGallery(),
                Workers = _workerRepository.Collection().ToList()
            };

            return View(viewModel);
        }
        [HttpPost]
        public ActionResult Create(WorkerGallery workerGallery, HttpPostedFileBase file)
        {
            if (!ModelState.IsValid)
            {
                return View(workerGallery);
            }
            else
            {
                if (file != null)
                {
                    workerGallery.GalleryUrl = workerGallery.WorkerImageGalleryId+ Path.GetFileNameWithoutExtension(file.FileName) + ".jpg";
                    file.SaveAs(Server.MapPath("//Content//Galleries//") + workerGallery.GalleryUrl);
                }
                _workerGalleryRepository.Insert(workerGallery);
                _workerGalleryRepository.Commit();

                return RedirectToAction("Index");
            }
        }
        public ActionResult Edit(int Id)
        {
            WorkerGallery galleryToEdit = _workerGalleryRepository.Find(Id);
            if (galleryToEdit == null)
            {
                return HttpNotFound();
            }
            else
            {
                WorkerGalleryViewModel viewModel = new WorkerGalleryViewModel();
                viewModel.Workers = _workerRepository.Collection().ToList();
                viewModel.WorkerGallery = galleryToEdit;

                return View(viewModel);
            }
        }
        [HttpPost]
        public ActionResult Edit(int id, WorkerGallery gallery, HttpPostedFileBase file)
        {
            WorkerGallery galleryToEdit = _workerGalleryRepository.Find(id);
            if (galleryToEdit == null)
            {
                return HttpNotFound();
            }
            else
            {
                if (!ModelState.IsValid)
                {
                    return View(galleryToEdit);
                }
                if (file != null)
                {
                    gallery.GalleryUrl = gallery.WorkerImageGalleryId + Path.GetFileNameWithoutExtension(file.FileName) + ".jpg";
                    file.SaveAs(Server.MapPath("//Content//Galleries//") + gallery.GalleryUrl);
                }
                galleryToEdit.GalleryName = gallery.GalleryName;
                galleryToEdit.WorkerId = gallery.WorkerId;
                
                _workerGalleryRepository.Commit();

                return RedirectToAction("Index");
            }
        }
        public ActionResult Delete(int Id)
        {
            WorkerGallery gallery = _workerGalleryRepository.Find(Id);
            if (gallery == null)
            {
                return HttpNotFound();
            }
            else
            {
                return View(gallery);
            }
        }
        [HttpPost]
        [ActionName("Delete")]
        public ActionResult ConfirmDelete(int Id)
        {
            WorkerGallery galleryToDelete = _workerGalleryRepository.Find(Id);
            if (galleryToDelete == null)
            {
                return HttpNotFound();
            }
            else
            {
                _workerGalleryRepository.Delete(Id);
                _workerGalleryRepository.Commit();

                return RedirectToAction("Index");
            }
        }

    }
}

WorkManagement/WorkManagement.MVCUI/Controllers/WorkerManagerController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WorkManagement.Core.Contracts;
using WorkManagement.Core.Models;
using WorkManagement.Core.ViewModels;

namespace WorkManagement.MVCUI.Controllers
{
    public class WorkerManagerController : Controller
    {
        IRepository<Worker> _workerRepository;
        IRepository<Department> _departmentRepository;
        IRepository<WorkerGallery> _workerGalleryRepository;
       
        public WorkerManagerController(IRepository<Worker> workerRepository, IRepository<Department> departmentRepository,
            IRepository<WorkerGallery> workerGalleryRepository)
        {
            _workerRepository = workerRepository;
            _departmentRepository = departmentRepository;
            _workerGalleryRepository = workerGalleryRepository;
           
        }
        // GET: WorkerManeger
        public ActionResult Index()
        {
            List<Worker> workerList = _workerRepository.Collection().ToList();

            return View(workerList);
        }
        public ActionResult Details(int Id)
        {
            Worker worker = _workerRepository.Find(Id);
            if (worker == null)
            {
                return HttpNotFound();
            }
            else
            {
                return View(worker);
            }
        }
      
        public ActionResult WorkerGallery(int Id)
        {
            Worker worker = _workerRepository.Find(Id);
            if (worker==null)
            {
                return HttpNotFound();
            }
            else
            {
                List<WorkerGallery> workerGalleries = _workerGalleryRepository.Collection().Where(x => x.WorkerId == worker.WorkerId).ToList();
                return View(workerGalleries);
            }
        }
        public ActionResult Create()
        {
            WorkerViewModel viewModel = new WorkerViewModel()
            {
                Worker = new Worker(),
                Departments = _departmentRepository.Collection().ToList()
            };
            return View(viewModel);

        }
        [HttpPost]
        public ActionResult Create(Worker worker, HttpPostedFileBase file)
        {
            if (!ModelState.IsValid)
            {
                return View(worker);
            }
            else
            {
                if (file != null)
                {
                    worker.WorkerImageUrl = worker.WorkerId + Path.GetFileNameWithoutExtension(file.FileName) + ".jpg";
                    file.SaveAs(Server.MapPath("//Content//WorkerProfileImages//") + worker.WorkerImageUrl);
                }
                _workerRepository.Insert(worker);
                _workerRepository.Commit();
                return RedirectToAction("Index");
            }

        }
        public ActionResult Edit(int Id)
        {
            Worker workerToEdit = _workerRepository.Find(Id);
            if (workerToEdit == null)
            {
                return HttpNotFound();
            }
            else
            {
                WorkerViewModel viewModel = new WorkerViewModel()
                {
                    Worker = workerToEdit,
                    Departments = _departmentRepository.Collection().ToList()
                };
                return View(viewModel);
            }
        }
        [HttpPost]
        public ActionResult Edit(int Id, Worker worker, HttpPostedFileBase file)
        {
            Worker workerToEdit = _workerRepository.Find(Id);
            if (workerToEdit == null)
            {
                return HttpNotFound();
            }
            else
            {
                if (!ModelState.IsValid)
                {
                    return View(workerToEdit);
                }
                if (file != null)
                {
                    workerToEdit.WorkerImageUrl = worker.WorkerId + Path.GetFileNameWithoutExtension(file.FileName) + ".jpg";
                    file.SaveAs(Server.MapPath("//Content//WorkerProfileImages//") + workerToEdit.WorkerImageUrl);
                }
                workerToEdit.FirstName = worker.FirstName;
                workerToEdit.LastName = worker.LastName;
                workerToEdit.Salary = worker.Salary;
                workerToEdit.DateOfBirth = worker.DateOfBirth;
                workerToEdit.DepartmentId = worker.DepartmentId;
                workerToEdit.Gender = worker.Gender;


                _workerRepository.Commit();

                return RedirectToAction("Index");

            }
        }
        public ActionResult Delete(int Id)
        {
            Worker worker = _workerRepository.Find(Id);
            if (worker == null)
            {
                return HttpNotFound();
            }
            else
            {
                return View(worker);
            }
        }
        [HttpPost]
        [ActionName("Delete")]
        public ActionResult ConfirmDeleted(int Id)
        {
            Worker workerToDelete = _workerRepository.Find(Id);
            if (workerToDelete == null)
            {
                return HttpNotFound();
            }
            else
            {
                _workerRepository.Delete(Id);
                _workerRepository.Commit();

                return RedirectToAction("Index");
            }
        }
    }
}

WorkManagement/WorkManagement.MVCUI/Views/WorkerManager/Create.cshtml
@model WorkManagement.Core.ViewModels.WorkerViewModel
@{
    ViewBag.Title = "Create";
}

    <br />

@using (Html.BeginForm("Create","WorkerManager",FormMethod.Post,new {enctype="multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>New Worker</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(model => model.Worker.WorkerImageUrl, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="file" id="file" class="form-control" />
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Worker.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Worker.FirstName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Worker.FirstName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Worker.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Worker.LastName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Worker.LastName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Worker.Salary, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Worker.Salary, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Worker.Salary, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Worker.DateOfBirth, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Worker.DateOfBirth, "{0:yyyy.MM.dd}", new { htmlAttributes = new { @class = "form-control", type = "date" } })

        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Worker.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="radio">
                <label>
                    @Html.RadioButtonFor(model => model.Worker.Gender, true) Male
                </label>
                <label>
                    @Html.RadioButtonFor(model => model.Worker.Gender, false) Female
                </label>
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Worker.DepartmentId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.Worker.DepartmentId, new SelectList(Model.Departments, "DepartmentId", "DepartmentName"), new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WorkManagement/WorkManagement.MVCUI/Views/WorkerManager/Delete.cshtml
@model WorkManagement.Core.Models.Worker

@{
    ViewBag.Title = "Delete";
}

    <br />

<h3>Are you sure you want to delete this worker?</h3>
<div class="col-md-3">
    <div class="col-md-12">
        <img class="img-responsive" style="height:250px;" src="~/Content/WorkerProfileImages/@Model.WorkerImageUrl" />
    </div>
</div>
<div class="col-md-9">
   
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Start Date
        </dt>

        <dd>
           @Model.CreatedAt.ToString("dd.MM.yyyy")
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DepartmentId)
        </dt>

        <dd>
          @Model.Department.DepartmentName
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Salary)
        </dt>

        <dd>
           @String.Format("{0:c}",Model.Salary)
        </dd>

        <dt>
            Date Of Birth
        </dt>

        <dd>
            @Model.DateOfBirth.ToString("dd.MM.yyyy")
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
         @(Model.Gender==true?"Male":"Female")
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

<div class="form-actions no-color">
    @Html.ActionLink("Back to List", "Index") |
    <input type="submit" value="Delete" class="btn btn-danger" />
</div>
    }
</div>

WorkManagement/WorkManagement.MVCUI/Views/WorkerManager/Details.cshtml
@model WorkManagement.Core.Models.Worker

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>
<div class="col-md-3">
    <div class="col-md-12">
        <img class="img-responsive" style="height:250px" src="~/Content/WorkerProfileImages/@Model.WorkerImageUrl" />
    </div>
</div>

<div class="col-md-9">
  
    <hr />
    <dl class="dl-horizontal">

        <dt>
            Start Date
        </dt>

        <dd>
           @Model.CreatedAt.ToString("dd.MM.yyyy")
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DepartmentId)
        </dt>

        <dd>
            @Model.Department.DepartmentName
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Salary)
        </dt>

        <dd>
            @String.Format("{0:c}", Model.Salary)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateOfBirth)
        </dt>

        <dd>
            @Model.DateOfBirth.ToString("dd.MM.yyyy")
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @(Model.Gender==true?"Male":"Female")
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.WorkerId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WorkManagement/WorkManagement.MVCUI/Views/WorkerManager/Edit.cshtml
@model WorkManagement.Core.ViewModels.WorkerViewModel
@{
    ViewBag.Title = "Edit";
}

<h2>Edit This Worker</h2>


@using (Html.BeginForm("Edit", "WorkerManager", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
       
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        @Html.HiddenFor(model => model.Worker.WorkerId)

        <div class="col-md-3">
            <div class="form-group">
                <div class="col-md-10">
                    <img class="img-responsive" style="height:300px" src="~/Content/WorkerProfileImages/@Model.Worker.WorkerImageUrl" />
                    <input type="file" name="file" id="file" class="form-control" />
                </div>
            </div>
        </div>

        <div class="col-md-9">
            <div class="form-group">
                @Html.LabelFor(model => model.Worker.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Worker.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Worker.FirstName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Worker.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Worker.LastName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Worker.LastName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Worker.Salary, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Worker.Salary, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Worker.Salary, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Worker.DateOfBirth, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.Worker.DateOfBirth, "{0:yyyy-MM-dd}", htmlAttributes: new { @class = "form-control", type = "date" })
                    @Html.ValidationMessageFor(model => model.Worker.DateOfBirth, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Worker.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="radio">
                        <label>
                            @Html.RadioButtonFor(model => model.Worker.Gender, true) Male
                        </label>
                        <label>
                            @Html.RadioButtonFor(model => model.Worker.Gender, false) Female
                        </label>
                    </div>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Worker.DepartmentId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.Worker.DepartmentId, new SelectList(Model.Departments, "DepartmentId", "DepartmentName"), new { @class = "form-control" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-success" />
                </div>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-default" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WorkManagement/WorkManagement.MVCUI/Views/WorkerManager/Index.cshtml
@model IEnumerable<WorkManagement.Core.Models.Worker>

@{
    ViewBag.Title = "Index";
}

<h2>Workers List</h2>

<p>
    @Html.ActionLink("Create a New Worker", "Create",null,new {@class="btn btn-primary" })
</p>
<table class="table">
    <tr>
        <th>
        </th>

        <th>
            Start Date
        </th>
        <th>
            Department Name
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.Salary)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateOfBirth)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Gender)
        </th>

        <th></th>
    </tr>

@foreach (var item in Model) {
<tr>
    <td>
        <img class="img-rounded" style="height:100px" src="~/Content/WorkerProfileImages/@item.WorkerImageUrl" />
    
        @Html.ActionLink("Go to Gallery", "WorkerGallery", new { id = item.WorkerId }, new { @class = "btn btn-default" })
    </td>
    <td>
        @item.CreatedAt.ToString("dd.MM.yyyy")
    </td>
    <td>
        @item.Department.DepartmentName
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.FirstName)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.LastName)
    </td>

    <td>
        @String.Format("{0:c}", item.Salary)
    </td>
    <td>
        @item.DateOfBirth.ToString("dd.MM.yyyy")
    </td>
    <td>
        @(item.Gender==true?"Male":"Female")
    </td>


    <td>
        @Html.ActionLink("Details", "Details", new { id = item.WorkerId }, new { @class = "btn btn-default" }) |
        @Html.ActionLink("Edit", "Edit", new { id = item.WorkerId }, new { @class = "btn btn-warning" }) |
        @Html.ActionLink("Delete", "Delete", new { id = item.WorkerId }, new { @class = "btn btn-danger" })
    </td>
</tr>
}

</table>

WorkManagement/WorkManagement.MVCUI/Views/WorkerManager/WorkerGallery.cshtml
@model IEnumerable<WorkManagement.Core.Models.WorkerGallery>

@{
    ViewBag.Title = "Index";
}

<br />

<h4>
    @Html.ActionLink("Create a New Gallery", "Create","WorkerGalleryManager", null, new { @class = "btn btn-primary" })
</h4>

<div class="col-md-12">

    @foreach (var item in Model)
    {
        <div class="col-md-3" style="height:300px;margin:10px;padding:10px;border:solid thin whitesmoke">
            <div class="col-md-12">
                <img class="img-responsive" style="height:180px" src="~/Content/Galleries/@item.GalleryUrl" />
            </div>
            <div class="col-md-12">
                <strong>@item.GalleryName</strong>
            </div>
            <div class="col-md-12">
                @item.CreatedAt.ToString("dd.MM.yyyy")
            </div>
            <div class="col-md-12">
                @Html.ActionLink("Visit Gallery", "GalleryImages", "WorkerGalleryManager",new {id=item.WorkerImageGalleryId },new {@class="btn btn-default" })
            </div>
           
        </div>
    }
</div>
@Html.ActionLink("Back to User List","Index",null,new {@class="btn btn-default" })
<div class="col-md-12 clearfix"></div>